### ISSUE TITLE
Fix Floating-Point Number Calculations in Contract

### ISSUE THREAD

**Issue by mart1n-xyz** [logos-co/staking#24] opened 2023-09-27 12:16 UTC
There are potential issues with how our contract handles calculations that require floating-point precision. Solidity doesn't natively support floating-point numbers, and our current approach may result in errors or lost precision.

Consider introducing fixed-point arithmetic by scaling numbers to maintain precision. Or utilize libraries or tools that can help in managing and maintaining precision in mathematical operations.

**Comment by 3esmit** [comment] 2024-02-25 00:57
Sorry for creating a duplicate of this.

**Comment by 0x-r4bbit** [comment] 2024-02-26 07:39
Let's close this one in favour of #64 as #64 is more elaborate and has some research notes attached to it.

**Closed by 0x-r4bbit** 2024-02-26 07:39 UTC
Labels: type: bug, priority: high
